02:20:29 INFO :::MainProcess::: [connexion.py> __enter__ >35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024EA92A3A40>
02:20:29 INFO :::MainProcess::: [connexion.py> __enter__ >37] ->> Cursor generado <sqlite3.Cursor object at 0x0000024EA9C64BC0>
02:20:29 WARNING :::MainProcess::: [connexion.py> __exit__ >43] ->> Ocurrió un error se genero un Rollback
02:20:29 ERROR :::MainProcess::: [connexion.py> __exit__ >44] ->> near "WHERE": syntax error
<class 'sqlite3.OperationalError'>
02:20:29 ERROR :::MainProcess::: [dao.py> regNota >230] ->> No se pudo realizar el registro: near "WHERE": syntax error
02:24:52 INFO :::MainProcess::: [connexion.py> __enter__ >35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C231AC3B40>
02:24:52 INFO :::MainProcess::: [connexion.py> __enter__ >37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C2323C47C0>
02:24:52 INFO :::MainProcess::: [dao.py> regNota >228] ->> 1 registro fue ingresado.
02:24:52 INFO :::MainProcess::: [connexion.py> __exit__ >46] ->> Interaccion finalizada
02:29:36 INFO :::MainProcess::: [connexion.py> __enter__ >35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E95D7C3B40>
02:29:36 INFO :::MainProcess::: [connexion.py> __enter__ >37] ->> Cursor generado <sqlite3.Cursor object at 0x000001E95E1647C0>
02:29:36 INFO :::MainProcess::: [dao.py> regNota >228] ->> 1 registro fue ingresado.
02:29:36 INFO :::MainProcess::: [connexion.py> __exit__ >46] ->> Interaccion finalizada
02:31:14 INFO :::MainProcess::: [connexion.py> __enter__ >35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000023202683B40>
02:31:14 INFO :::MainProcess::: [connexion.py> __enter__ >37] ->> Cursor generado <sqlite3.Cursor object at 0x0000023202F547C0>
02:31:14 INFO :::MainProcess::: [dao.py> regNota >228] ->> 1 registro fue ingresado.
02:31:14 INFO :::MainProcess::: [connexion.py> __exit__ >46] ->> Interaccion finalizada
02:32:06 INFO :::MainProcess::: [connexion.py: __enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000013790AD3A40>
02:32:06 INFO :::MainProcess::: [connexion.py: __enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000013791404BC0>
02:32:06 INFO :::MainProcess::: [dao.py: regNota Line: 228] ->> 1 registro fue ingresado.
02:32:06 INFO :::MainProcess::: [connexion.py: __exit__ Line: 46] ->> Interaccion finalizada
02:33:41 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E14E1B3A40>
02:33:41 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001E14EB54BC0>
02:33:41 INFO :::dao.py::: [regNota Line: 228] ->> 1 registro fue ingresado.
02:33:41 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
02:36:23 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002849F193B40>
02:36:23 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002849FB347C0>
02:36:23 INFO :::dao.py::: [_check_point Line: 198] ->> Registros encontrados: 4
02:36:23 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
02:50:21 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002406F9A3B40>
02:50:21 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002406FF24840>
02:50:21 INFO :::dao.py::: [noteUpdate Line: 244] ->> 1 registro se actualizo correctamente.
02:50:21 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
03:12:12 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E2B4133B40>
03:12:12 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001E2B4A84840>
03:12:12 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
03:12:12 ERROR :::connexion.py::: [__exit__ Line: 44] ->> no such column: F_not
<class 'sqlite3.OperationalError'>
03:18:02 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002A926473B40>
03:18:02 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002A9269F4840>
03:18:02 INFO :::dao.py::: [delNote Line: 258] ->> 1 registro ha sido eliminado.
03:18:02 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
03:47:54 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F2E57B3A40>
03:47:54 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001F2E5D34840>
03:47:54 INFO :::dao.py::: [prod_reg Line: 291] ->> 1 producto ha sido registrado
03:47:54 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
03:50:26 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002036FD93A40>
03:50:26 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000020370744840>
03:50:26 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
03:50:26 ERROR :::connexion.py::: [__exit__ Line: 44] ->> UNIQUE constraint failed: Productos.id_clave
<class 'sqlite3.IntegrityError'>
03:51:42 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000027966783A40>
03:51:42 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000027966D04840>
03:51:42 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
03:51:42 ERROR :::connexion.py::: [__exit__ Line: 44] ->> UNIQUE constraint failed: Productos.id_clave
<class 'sqlite3.IntegrityError'>
03:51:48 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E363113A40>
03:51:48 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001E363A54840>
03:51:48 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
03:51:48 ERROR :::connexion.py::: [__exit__ Line: 44] ->> UNIQUE constraint failed: Productos.id_clave
<class 'sqlite3.IntegrityError'>
03:53:03 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000206DDAF3A40>
03:53:03 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x00000206DE464840>
03:53:03 INFO :::dao.py::: [prod_reg Line: 291] ->> 1 producto ha sido registrado
03:53:03 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
03:55:51 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C9C3F13A40>
03:55:51 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C9C4494840>
03:55:51 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
03:55:51 ERROR :::connexion.py::: [__exit__ Line: 44] ->> table Productos has no column named descripcio
<class 'sqlite3.OperationalError'>
04:52:00 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002C341833A40>
04:52:00 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002C342114940>
04:52:00 INFO :::dao.py::: [_check_point Line: 279] ->> Registros encontrados: 2
04:52:00 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
04:52:36 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002ACD4E03A40>
04:52:36 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002ACD5384940>
04:52:36 INFO :::dao.py::: [_check_point Line: 279] ->> Registros encontrados: 1
04:52:36 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
04:55:27 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001955E4B3A40>
04:55:27 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001955EA34940>
04:55:27 INFO :::dao.py::: [_check_point Line: 279] ->> Registros encontrados: 1
04:55:27 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
04:55:42 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001AD7AD03A40>
04:55:42 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001AD7B604940>
04:55:42 INFO :::dao.py::: [_check_point Line: 279] ->> Registros encontrados: 1
04:55:42 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:29:18 WARNING :::dao.py::: [prodUpdate Line: 373] ->> descripcion no es una opción valida.
06:29:45 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C5ACAD3B40>
06:29:45 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C5AD054940>
06:29:45 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:29:45 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C5ACAD3940>
06:29:45 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C5AD39D640>
06:29:45 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
06:29:45 ERROR :::connexion.py::: [__exit__ Line: 44] ->> near "WHERE": syntax error
<class 'sqlite3.OperationalError'>
06:33:09 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C665C83B40>
06:33:09 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C666204940>
06:33:09 INFO :::dao.py::: [prodUpdate Line: 364] ->> 0 Registro actualizado: Descripcion
06:33:09 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:33:09 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C665C83A40>
06:33:09 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001C66628E0C0>
06:33:09 WARNING :::connexion.py::: [__exit__ Line: 43] ->> Ocurrió un error se genero un Rollback
06:33:09 ERROR :::connexion.py::: [__exit__ Line: 44] ->> near "WHERE": syntax error
<class 'sqlite3.OperationalError'>
06:34:55 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024829643B40>
06:34:55 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000024829BC4940>
06:34:55 INFO :::dao.py::: [prodUpdate Line: 364] ->> 0 Registro actualizado: Descripcion
06:34:55 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:34:55 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024829643A40>
06:34:55 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000024829C4E0C0>
06:34:55 INFO :::dao.py::: [prodUpdate Line: 354] ->> 0 Registro actualizado: Costo
06:34:55 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:34:55 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024829643B40>
06:34:55 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000024829BC4940>
06:34:55 INFO :::dao.py::: [prodUpdate Line: 349] ->> 0 Registro actualizado: Cantidad
06:34:55 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:35:23 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B2B12F3B40>
06:35:23 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001B2B1874940>
06:35:23 INFO :::dao.py::: [prodUpdate Line: 365] ->> 0 Registro actualizado: Descripcion
06:35:23 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:35:23 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B2B12F3A40>
06:35:23 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001B2B18FE0C0>
06:35:23 INFO :::dao.py::: [prodUpdate Line: 355] ->> 0 Registro actualizado: Costo
06:35:23 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:35:23 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B2B12F3B40>
06:35:23 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001B2B1874940>
06:35:23 INFO :::dao.py::: [prodUpdate Line: 350] ->> 0 Registro actualizado: Cantidad
06:35:23 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:38:59 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000214C8C93B40>
06:38:59 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x00000214C9214940>
06:38:59 INFO :::dao.py::: [prodUpdate Line: 364] ->> 0 Registro actualizado: description
06:38:59 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:38:59 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000214C8C93A40>
06:38:59 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x00000214C929E0C0>
06:38:59 INFO :::dao.py::: [prodUpdate Line: 354] ->> 0 Registro actualizado: cost
06:38:59 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:38:59 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000214C8C93B40>
06:38:59 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x00000214C9214940>
06:38:59 INFO :::dao.py::: [prodUpdate Line: 349] ->> 0 Registro actualizado: cantidad
06:38:59 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:39:34 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000029B18833A40>
06:39:34 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000029B191D4940>
06:39:34 INFO :::dao.py::: [prodUpdate Line: 364] ->> 0 Registro actualizado: description
06:39:34 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:46:24 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F117F53A40>
06:46:24 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001F1184D4940>
06:46:24 INFO :::dao.py::: [prodUpdate Line: 369] ->> 0 Registro actualizado: description
06:46:24 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:47:59 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002826C313A40>
06:47:59 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000002826C894940>
06:47:59 INFO :::dao.py::: [prodUpdate Line: 369] ->> 1 Registro actualizado: description
06:47:59 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:48:39 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000017C29A93B40>
06:48:39 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000017C2A014940>
06:48:39 INFO :::dao.py::: [prodUpdate Line: 357] ->> 1 Registro actualizado: cost
06:48:39 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:48:39 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000017C29A93A40>
06:48:39 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000017C2A09E0C0>
06:48:39 INFO :::dao.py::: [prodUpdate Line: 351] ->> 1 Registro actualizado: cantidad
06:48:39 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
06:51:40 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000026055503A40>
06:51:40 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x0000026055DE4940>
06:51:40 INFO :::dao.py::: [prodUpdate Line: 369] ->> 1 Registro actualizado: out
06:51:40 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
07:09:04 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E5E9A03A40>
07:09:04 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x000001E5EA3049C0>
07:09:04 INFO :::dao.py::: [prodDel Line: 395] ->> 0 registro ha sido eliminado.
07:09:04 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
07:09:34 INFO :::connexion.py::: [__enter__ Line: 35] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000291ED933A40>
07:09:34 INFO :::connexion.py::: [__enter__ Line: 37] ->> Cursor generado <sqlite3.Cursor object at 0x00000291EDEB49C0>
07:09:34 INFO :::dao.py::: [prodDel Line: 395] ->> 1 registro ha sido eliminado.
07:09:34 INFO :::connexion.py::: [__exit__ Line: 46] ->> Interaccion finalizada
