10:08:24: INFO -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:24: WARNING -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:24: ERROR -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:24: CRITICAL -<MainProcess>- [log_gen.py: <module>] ->> Test exitoso
10:08:40 INFO -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:40 WARNING -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:40 ERROR -<MainProcess>- [log_gen.py: <module>] ->> Prueba Exitosa
10:08:40 CRITICAL -<MainProcess>- [log_gen.py: <module>] ->> Test exitoso
11:12:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000014219753D40>
11:12:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000014219CD47C0>
11:12:08 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
11:13:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000014B21C43D40>
11:13:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000014B221C43C0>
11:13:30 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un rollback {except_val}
11:13:53 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B295D03D40>
11:13:53 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001B2962843C0>
11:13:53 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un rollback no such table: Clentes
11:15:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001911FAA3D40>
11:15:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000191203B4440>
11:15:30 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
11:15:30 ERROR -<MainProcess>- [connexion.py: __exit__] ->> <class 'sqlite3.OperationalError'>: no such table: Clentes
11:16:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002044E713D40>
11:16:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002044EC943C0>
11:16:20 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
11:16:20 ERROR -<MainProcess>- [connexion.py: __exit__] ->> <class 'sqlite3.OperationalError'>:<traceback object at 0x000002044ECAAB40> no such table: Clentes
11:17:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D99AC03D40>
11:17:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D99B184440>
11:17:08 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
11:17:08 ERROR -<MainProcess>- [connexion.py: __exit__] ->> <class 'type'>:no such table: Clentes
11:17:41 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024B70F93D40>
11:17:41 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000024B718E4440>
11:17:41 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
11:17:41 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un problema:no such table: Clentes
11:18:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000200B1253D40>
11:18:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000200B1C14440>
11:18:03 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
11:18:03 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un problema:no such table: Clentes
11:19:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002327E853D40>
11:19:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002327F174440>
11:19:40 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:17:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000221C66E3D40>
01:17:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000221C6FF4940>
01:17:27 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:17:27 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
01:18:01 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B74BA23D40>
01:18:01 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001B74BFA44C0>
01:18:01 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:18:01 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
01:20:58 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D4E4F33D40>
01:20:58 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D4E58B4440>
01:20:58 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:20:58 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
01:22:42 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001ED3E2E3D40>
01:22:42 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001ED3E8644C0>
01:22:42 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:22:42 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
01:23:19 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000013BB6B23D40>
01:23:19 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000013BB74A44C0>
01:23:19 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:23:19 ERROR -<MainProcess>- [connexion.py: __exit__] ->> no such column: Nombre
<class 'sqlite3.OperationalError'>
01:23:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000120CD703D40>
01:23:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000120CDC844C0>
01:23:45 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:24:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000011CC1AE3D40>
01:24:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000011CC20644C0>
01:24:07 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:24:07 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
12:41:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000028ADDD33D40>
12:41:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000028ADE2B44C0>
12:41:32 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:52:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000016F50A73D40>
12:52:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000016F50FF4540>
12:52:51 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:53:25 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000025F50783D40>
12:53:25 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000025F50D04540>
12:53:25 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:53:46 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001A814703D40>
12:53:46 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001A8150C44C0>
12:53:46 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:54:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000151FFE83D40>
12:54:08 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000151807F44C0>
12:54:08 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:58:21 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002B5AE023D40>
12:58:21 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002B5AE5A44C0>
12:58:21 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
12:58:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000277D4803D40>
12:58:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000277D4D844C0>
12:58:48 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:29:57 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000222C5453D40>
01:29:57 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000222C59D44C0>
01:29:57 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:29:57 ERROR -<MainProcess>- [connexion.py: __exit__] ->> no such table: Cliente
<class 'sqlite3.OperationalError'>
01:35:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001B33C403D40>
01:35:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001B33C9844C0>
01:35:40 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:36:04 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000015A05F93D40>
01:36:04 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000015A065144C0>
01:36:04 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:38:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001A8B58C3D40>
01:38:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001A8B62644C0>
01:38:20 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:39:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F465533D40>
01:39:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001F465AB4540>
01:39:07 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:39:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D6F7853D40>
01:39:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D6F7DD4540>
01:39:27 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:53:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001FED2183D40>
01:53:20 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001FED2704540>
01:53:20 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:53:43 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024DAC153D40>
01:53:43 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000024DAC6D4540>
01:53:43 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:54:26 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024D32BA3D40>
01:54:26 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000024D33124540>
01:54:26 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:54:26 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
01:55:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F47E213D40>
01:55:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001F47E794540>
01:55:03 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:55:03 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Incorrect number of bindings supplied. The current statement uses 2, and there are 3 supplied.
<class 'sqlite3.ProgrammingError'>
01:55:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D3B2453D40>
01:55:27 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D3B29D4540>
01:55:27 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:55:27 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Error binding parameter 0 - probably unsupported type.
<class 'sqlite3.InterfaceError'>
01:55:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000011D241C3D40>
01:55:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000011D24AD4540>
01:55:48 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:55:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000013963ED3D40>
01:55:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000013964844540>
01:55:56 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:56:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000242B22D3D40>
01:56:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000242B2C74540>
01:56:32 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
01:57:57 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000192F7303D40>
01:57:57 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000192F7C346C0>
01:57:57 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
01:57:57 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
<class 'sqlite3.ProgrammingError'>
01:58:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000152FA483D40>
01:58:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000152FAA04740>
01:58:15 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
03:22:19 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
'NoneType' object is not subscriptable
03:30:49 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:31:18 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:33:16 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:33:42 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:52:15 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:52:42 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
03:52:58 ERROR -<MainProcess>- [client.py: __init__] ->> No se pudo generar la clave:
can only concatenate str (not "NoneType") to str
05:24:00 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D8D7C23A40>
05:24:00 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D8D85C45C0>
05:24:00 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:24:00 ERROR -<MainProcess>- [connexion.py: __exit__] ->> table Clientes has no column named Nombre
<class 'sqlite3.OperationalError'>
05:24:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002C607343A40>
05:24:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002C6078C45C0>
05:24:45 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:29:11 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002611DAF3840>
05:29:11 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002611E0745C0>
05:29:11 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:30:34 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001D0E4F83940>
05:30:34 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001D0E5894740>
05:30:34 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:30:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001EB1E0E3940>
05:30:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001EB1E664740>
05:30:55 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:31:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000016420D73940>
05:31:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000164212F46C0>
05:31:51 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:33:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000020F113E3940>
05:33:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000020F11964640>
05:33:45 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:33:45 ERROR -<MainProcess>- [connexion.py: __exit__] ->> incomplete input
<class 'sqlite3.OperationalError'>
05:34:24 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000020E3B5A3940>
05:34:24 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000020E3BF24640>
05:34:24 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:34:24 ERROR -<MainProcess>- [connexion.py: __exit__] ->> incomplete input
<class 'sqlite3.OperationalError'>
05:38:01 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002946DFF3940>
05:38:01 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002946E8D4640>
05:38:01 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:38:01 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Incorrect number of bindings supplied. The current statement uses 1, and there are 6 supplied.
<class 'sqlite3.ProgrammingError'>
05:38:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000199171D3940>
05:38:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000019917B04640>
05:38:44 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:39:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000015FE5883940>
05:39:07 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000015FE5E04640>
05:39:07 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:39:07 ERROR -<MainProcess>- [connexion.py: __exit__] ->> incomplete input
<class 'sqlite3.OperationalError'>
05:40:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000014E84E53940>
05:40:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000014E857D4640>
05:40:32 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:40:32 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "?": syntax error
<class 'sqlite3.OperationalError'>
05:40:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000025609123940>
05:40:51 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000256096A4640>
05:40:51 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:40:51 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
05:41:02 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001FC1AA13940>
05:41:02 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001FC1B304640>
05:41:02 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:41:02 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
05:41:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001A0D9EF3940>
05:41:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001A0DA474640>
05:41:23 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:41:23 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Incorrect number of bindings supplied. The current statement uses 0, and there are 3 supplied.
<class 'sqlite3.ProgrammingError'>
05:41:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000256956F3940>
05:41:40 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000025696004640>
05:41:40 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:41:40 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "?": syntax error
<class 'sqlite3.OperationalError'>
05:41:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000019006243940>
05:41:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000190067C4640>
05:41:55 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:41:55 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near ",": syntax error
<class 'sqlite3.OperationalError'>
05:42:35 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000254CEE53940>
05:42:35 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000254CF3D4640>
05:42:35 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:42:35 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
05:43:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F705EE3940>
05:43:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001F706464640>
05:43:48 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:43:48 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "%": syntax error
<class 'sqlite3.OperationalError'>
05:44:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000023442843940>
05:44:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000023442DC4640>
05:44:03 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:44:03 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "?": syntax error
<class 'sqlite3.OperationalError'>
05:44:19 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001CB85E53940>
05:44:19 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001CB863D4640>
05:44:19 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:44:19 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "?": syntax error
<class 'sqlite3.OperationalError'>
05:49:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C6653E3940>
05:49:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001C665D14640>
05:49:45 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:49:45 ERROR -<MainProcess>- [connexion.py: __exit__] ->> near "*": syntax error
<class 'sqlite3.OperationalError'>
05:50:12 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000020143A63940>
05:50:12 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000020143FE4640>
05:50:12 WARNING -<MainProcess>- [connexion.py: __exit__] ->> Ocurrió un error se genero un Rollback
05:50:12 ERROR -<MainProcess>- [connexion.py: __exit__] ->> Incorrect number of bindings supplied. The current statement uses 0, and there are 1 supplied.
<class 'sqlite3.ProgrammingError'>
05:50:36 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001831C983940>
05:50:36 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001831CF04640>
05:50:36 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:57:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E3DE483940>
05:57:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001E3DEDF4640>
05:57:15 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:57:28 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001F0DC0F3940>
05:57:28 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001F0DCA74640>
05:57:28 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:57:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000144E3DD3940>
05:57:48 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000144E4754640>
05:57:48 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:58:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000263794B3940>
05:58:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000026379A34640>
05:58:06 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:58:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000258A50A3940>
05:58:45 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000258A5624640>
05:58:45 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
05:59:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001FEDAFC3940>
05:59:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001FEDB544640>
05:59:15 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:00:42 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000207C14D3940>
06:00:42 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000207C1E14640>
06:00:42 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:01:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002191B563940>
06:01:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002191BE44640>
06:01:06 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:02:52 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000281BE6D3940>
06:02:52 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000281BF014540>
06:02:52 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:11:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000024A6B733940>
06:11:55 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000024A6BCB44C0>
06:11:55 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 12
06:11:55 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:15:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000106219C3940>
06:15:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000010621F444C0>
06:15:44 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: 1125846818752
06:15:44 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:16:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x00000256A26A3940>
06:16:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x00000256A2C245C0>
06:16:06 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: 0x256a2811fc0
06:16:06 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:16:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002561DC13940>
06:16:30 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002561E5C45C0>
06:16:30 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: 0x2561e1b1fc0
06:16:30 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:17:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001CACD823940>
06:17:06 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001CACDDA45C0>
06:17:06 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: <Client.register 0x1cacd991fc0>
06:17:06 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:17:22 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000018E9D043940>
06:17:22 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000018E9D5C45C0>
06:17:22 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: <Client.register object 0x18e9d1b1fc0>
06:17:22 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
06:21:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001C43E183940>
06:21:32 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001C43EA54540>
06:21:32 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 2
06:21:32 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:31:46 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E5669A3840>
07:31:46 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001E566F24540>
07:31:46 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 2
07:31:46 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:34:00 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000021BF5393840>
07:34:00 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000021BF5914540>
07:34:00 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 2
07:34:00 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:35:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E9A0623840>
07:35:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001E9A0BA4540>
07:35:23 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 2
07:35:23 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:35:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001E9A0623740>
07:35:23 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001E9A0BA4540>
07:35:23 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:41:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001EEC2F73940>
07:41:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001EEC3934540>
07:41:56 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 3
07:41:56 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:41:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001EEC2F73840>
07:41:56 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001EEC3934540>
07:41:56 INFO -<MainProcess>- [dao_client.py: singup] ->> Registro completado
07:41:56 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:44:33 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002308FE33940>
07:44:33 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000023090764540>
07:44:33 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 4
07:44:33 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:44:33 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002308FE33840>
07:44:33 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000023090764540>
07:44:33 INFO -<MainProcess>- [dao_client.py: singup] ->> Cliente: PI-176AOAO1239 registrado.
07:44:33 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:46:37 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002A9E24D3940>
07:46:37 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002A9E2E24540>
07:46:37 INFO -<MainProcess>- [dao_client.py: check_point] ->> Registros encontrados: 5
07:46:37 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:47:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000002548C0E3940>
07:47:44 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000002548CA44640>
07:47:44 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: <Client.register object at 0x2548c631cf0>
07:47:44 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:49:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x000001EB76D23940>
07:49:03 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x000001EB772A4640>
07:49:03 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: Jonathan Mesach
07:49:03 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
07:49:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Conexion Exitosa <sqlite3.Connection object at 0x0000025BA0FB3940>
07:49:15 INFO -<MainProcess>- [connexion.py: __enter__] ->> Cursor generado <sqlite3.Cursor object at 0x0000025BA1534640>
07:49:15 INFO -<MainProcess>- [dao_client.py: load_client] ->> Registe encontrado: CN-1702JHVS8242
07:49:15 INFO -<MainProcess>- [connexion.py: __exit__] ->> Operacion exitosa
